security:
  user:
    password: password
server:
  port: 8082
spring:
  session:
    store-type: redis
zuul:
  routes:
    resource:
      path: /fulfillment/**
      url: http://localhost:8083/fulfillment
      sensitive-headers: